package runtime

import (
	"fmt"
	"os"
)

// surface_sync.go holds the shared primitive for the "raw/read-only
// materialization" half of the File-SST+FUSE-gate pattern named in
// Paper/core/architecture/layering.md ("File as SST + FUSE as validated
// write gate over it") and scoped for dedup by work order T4.2
// (Paper/_design/migrations/runtime-capability-registry-followups.md).
//
// The pattern has two shapes:
//
//   - raw/read-only materialization: content is fully regenerated by this
//     process and never mutated by peers, so it is written then marked
//     0444 — writeReadOnlyFile below.
//   - runtime-owned cache-file: content changes over the process lifetime
//     and is written via a temp-file-then-atomic-rename to avoid partial
//     reads by concurrent FUSE/peer readers, with no read-only bit.
//
// The runtime-owned-cache-file shape already had a single shared primitive
// — writeFile / writeTextFile / writeJSONFile (runtime.go) — used by all
// three surface-sync call sites T4.2 names (syncPublicSurface's degraded
// marker, the config_surface.go family, and syncInspectableWorldSurface's
// status.json/resources.json/workspace_root/workspace/events.jsonl/
// fs-mutations.latest), so no further extraction was needed for that half.
//
// The raw/read-only shape's write+chmod tail, by contrast, is used within
// config_surface.go by the drift-refreshed registry.json projection and the
// inc/<n-1>/override-applied.env archive (consumeAppliedEnvOverride).
// writeReadOnlyFile below is the extracted tail; each call site keeps its own
// distinct guard (a content-diff skip or an Lstat-exists skip) since those
// guards are the genuinely different part of each call site, not the
// duplicated part.
//
// syncPublicSurface's degraded marker and syncInspectableWorldSurface were
// deliberately left out of this extraction: neither one chmods anything
// 0444 — both materialize mutable, runtime-owned content via the
// already-shared atomic-write primitives, so they were never duplicating
// this shape in the first place. See the T4.2 row in
// runtime-capability-registry-followups.md's execution log for the full
// judgment call.
func writeReadOnlyFile(path string, data []byte, label string) error {
	if err := writeFile(path, data); err != nil {
		return err
	}
	if err := os.Chmod(path, 0o444); err != nil {
		return fmt.Errorf("chmod %s read-only: %w", label, err)
	}
	return nil
}
