package tools

import (
	"bytes"
	"encoding/base64"
	"image"
	"image/color"
	"image/jpeg"
	"image/png"
	"os"
	"path/filepath"
	"testing"

	"github.com/kehao95/quine/internal/tape"
)

func encodePNG(t *testing.T, width, height int, c color.Color) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, c)
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatalf("encode png: %v", err)
	}
	return buf.Bytes()
}

func encodeJPEG(t *testing.T, width, height int, c color.Color) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, c)
		}
	}
	var buf bytes.Buffer
	if err := jpeg.Encode(&buf, img, &jpeg.Options{Quality: 90}); err != nil {
		t.Fatalf("encode jpeg: %v", err)
	}
	return buf.Bytes()
}

func decodeVisionPayload(t *testing.T, result tape.ToolResult) map[string]any {
	t.Helper()
	payload, err := tape.UnmarshalStructuredToolResultContent(result.Content)
	if err != nil {
		t.Fatalf("decode vision payload: %v", err)
	}
	return payload
}

func TestDetectMIMETypePrefersMagicBytes(t *testing.T) {
	jpegData := encodeJPEG(t, 4, 4, color.RGBA{R: 255, A: 255})
	if got := detectMIMEType(jpegData, "fake.png"); got != "image/jpeg" {
		t.Fatalf("detectMIMEType() = %q, want image/jpeg", got)
	}
}

func TestDetectMIMETypeFallsBackToExtension(t *testing.T) {
	if got := detectMIMEType([]byte("not-really-an-image"), "fallback.png"); got != "image/png" {
		t.Fatalf("detectMIMEType() = %q, want image/png", got)
	}
}

func TestDetectMIMETypeRecognizesNetpbm(t *testing.T) {
	if got := detectMIMEType([]byte("P6\n1 1\n255\n\xff\x00\x00"), "sample.txt"); got != "image/x-portable-pixmap" {
		t.Fatalf("detectMIMEType() = %q, want image/x-portable-pixmap", got)
	}
	if got := detectMIMEType([]byte("not-really-an-image"), "sample.pgm"); got != "image/x-portable-graymap" {
		t.Fatalf("detectMIMEType() = %q, want image/x-portable-graymap", got)
	}
}

func TestHandleVisionReturnsImagePayload(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "sample.png")
	if err := os.WriteFile(path, encodePNG(t, 8, 8, color.RGBA{R: 255, A: 255}), 0o644); err != nil {
		t.Fatalf("write sample image: %v", err)
	}

	result := HandleVision("vision-1", map[string]any{
		"path":        path,
		"instruction": "name the dominant color",
	})
	if result.IsError {
		t.Fatalf("HandleVision() returned error: %s", string(result.Content))
	}
	if result.Image == nil {
		t.Fatal("HandleVision() returned nil image payload")
	}
	if result.Image.MIMEType != "image/png" {
		t.Fatalf("image mime = %q, want image/png", result.Image.MIMEType)
	}

	payload := decodeVisionPayload(t, result)
	if payload["status"] != "completed" {
		t.Fatalf("status = %#v, want completed", payload["status"])
	}
	if payload["mime_type"] != "image/png" {
		t.Fatalf("mime_type = %#v, want image/png", payload["mime_type"])
	}
	if payload["instruction"] != "name the dominant color" {
		t.Fatalf("instruction = %#v", payload["instruction"])
	}
}

func TestHandleVisionConvertsPPMToPNG(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "sample.ppm")
	data := []byte("P6\n# generated by a benchmark probe\n2 1\n255\n\xff\x00\x00\x00\xff\x00")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write sample ppm: %v", err)
	}

	result := HandleVision("vision-ppm", map[string]any{"path": path})
	if result.IsError {
		t.Fatalf("HandleVision() returned error: %s", string(result.Content))
	}
	if result.Image == nil {
		t.Fatal("HandleVision() returned nil image payload")
	}
	if result.Image.MIMEType != "image/png" {
		t.Fatalf("image mime = %q, want image/png", result.Image.MIMEType)
	}

	decoded, err := base64.StdEncoding.DecodeString(result.Image.Data)
	if err != nil {
		t.Fatalf("decode image payload: %v", err)
	}
	img, format, err := image.Decode(bytes.NewReader(decoded))
	if err != nil {
		t.Fatalf("decode converted image: %v", err)
	}
	if format != "png" {
		t.Fatalf("converted image format = %q, want png", format)
	}
	if bounds := img.Bounds(); bounds.Dx() != 2 || bounds.Dy() != 1 {
		t.Fatalf("converted image bounds = %v, want 2x1", bounds)
	}

	payload := decodeVisionPayload(t, result)
	if payload["mime_type"] != "image/png" {
		t.Fatalf("mime_type = %#v, want image/png", payload["mime_type"])
	}
}

func TestHandleVisionScalesLargeImage(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "large.png")
	if err := os.WriteFile(path, encodePNG(t, maxImageDimension+300, 200, color.RGBA{G: 255, A: 255}), 0o644); err != nil {
		t.Fatalf("write large image: %v", err)
	}

	result := HandleVision("vision-2", map[string]any{"path": path})
	if result.IsError {
		t.Fatalf("HandleVision() returned error: %s", string(result.Content))
	}

	payload := decodeVisionPayload(t, result)
	if payload["scaled"] != true {
		t.Fatalf("scaled = %#v, want true", payload["scaled"])
	}
}

func TestHandleVisionRejectsMissingPath(t *testing.T) {
	result := HandleVision("vision-3", map[string]any{})
	if !result.IsError {
		t.Fatal("HandleVision() should fail when path is missing")
	}
	payload := decodeVisionPayload(t, result)
	if payload["status"] != "error" {
		t.Fatalf("status = %#v, want error", payload["status"])
	}
}
