package config

const (
	EnvModelID                  = "QUINE_MODEL_ID"
	EnvAPIType                  = "QUINE_API_TYPE"
	EnvAPIBase                  = "QUINE_API_BASE"
	EnvAPIKey                   = "QUINE_API_KEY"
	EnvMaxDepth                 = "QUINE_MAX_DEPTH"
	EnvDepth                    = "QUINE_DEPTH"
	EnvSessionID                = "QUINE_SESSION_ID"
	EnvRunID                    = "QUINE_RUN_ID"
	EnvTapeID                   = "QUINE_TAPE_ID"
	EnvParentSession            = "QUINE_PARENT_SESSION"
	EnvMaxConcurrent            = "QUINE_MAX_CONCURRENT"
	EnvMaxAgents                = "QUINE_MAX_AGENTS"
	EnvForkDefaultTimeout       = "QUINE_FORK_DEFAULT_TIMEOUT_SECONDS"
	EnvShDefaultTimeout         = "QUINE_SH_DEFAULT_TIMEOUT_SECONDS"
	EnvShTimeout                = "QUINE_SH_TIMEOUT"
	EnvShTimeoutOverride        = "QUINE_SH_TIMEOUT_OVERRIDE_ENABLED"
	EnvShStdinEnabled           = "QUINE_SH_STDIN_ENABLED"
	EnvShDetachEnabled          = "QUINE_SH_DETACH_ENABLED"
	EnvOutputTruncate           = "QUINE_OUTPUT_TRUNCATE"
	EnvDataDir                  = "QUINE_DATA_DIR"
	EnvRetentionDir             = "QUINE_RETENTION_DIR"
	EnvWorkDir                  = "QUINE_WORK_DIR"
	EnvShell                    = "QUINE_SHELL"
	EnvShNetwork                = "QUINE_SH_NETWORK"
	EnvSelfReentryMode          = "QUINE_SELF_REENTRY_MODE"
	EnvSelfReentryTarget        = "QUINE_SELF_REENTRY_TARGET"
	EnvMaxTurns                 = "QUINE_MAX_TURNS"
	EnvWallClockExitSeconds     = "QUINE_WALL_CLOCK_EXIT_SECONDS"
	EnvTurnExhaustionPolicy     = "QUINE_TURN_EXHAUSTION_POLICY"
	EnvPromptMetaphor           = "QUINE_PROMPT_METAPHOR"
	EnvPromptSelfModel          = "QUINE_PROMPT_SELF_MODEL"
	EnvPromptInstructionSurface = "QUINE_PROMPT_INSTRUCTION_SURFACE"
	EnvPromptRuntimeSurface     = "QUINE_PROMPT_RUNTIME_SURFACE"
	EnvPromptPersona            = "QUINE_PROMPT_PERSONA"
	EnvPromptCtl                = "QUINE_PROMPT_CTL"
	EnvPromptImplDetails        = "QUINE_PROMPT_IMPL_DETAILS"
	EnvPromptBudgetVisibility   = "QUINE_PROMPT_BUDGET_VISIBILITY"
	EnvPeerDiscoveryEnabled     = "QUINE_PEER_DISCOVERY_ENABLED"
	EnvPeerDiscoveryHeartbeat   = "QUINE_PEER_DISCOVERY_HEARTBEAT_INTERVAL_MS"
	EnvFSMutationTelemetry      = "QUINE_FS_MUTATION_TELEMETRY_ENABLED"
	EnvFailOnImpossible         = "QUINE_FAIL_ON_IMPOSSIBLE"
	EnvNoMissionAutonomy        = "QUINE_NO_MISSION_AUTONOMY"
	EnvEmptyAssistantSuccess    = "QUINE_EMPTY_ASSISTANT_SUCCESS"
	EnvReadyTextAutoIdle        = "QUINE_READY_TEXT_AUTO_IDLE"
	EnvContextWindow            = "QUINE_CONTEXT_WINDOW"
	EnvThinkingBudget           = "QUINE_THINKING_BUDGET"
	EnvModelServiceTier         = "QUINE_MODEL_SERVICE_TIER"
	EnvMemoryWarnTokens         = "QUINE_MEMORY_WARN_TOKENS"
	EnvMemoryDangerTokens       = "QUINE_MEMORY_DANGER_TOKENS"
	EnvMemoryDeathTokens        = "QUINE_MEMORY_DEATH_TOKENS"
	EnvMemoryStrategyHints      = "QUINE_MEMORY_STRATEGY_HINTS"
	EnvConfigDir                = "QUINE_CONFIG_DIR"
	EnvAnchorMemory             = "QUINE_ANCHOR_MEMORY"
	EnvAnchorFoldEnabled        = "QUINE_ANCHOR_FOLD_ENABLED"
	EnvAnchorMarkEnabled        = "QUINE_ANCHOR_MARK_ENABLED"
	EnvIdleEnabled              = "QUINE_IDLE_ENABLED"
	EnvForkEnabled              = "QUINE_FORK_ENABLED"
	EnvExitEnabled              = "QUINE_EXIT_ENABLED"
	EnvExecEnabled              = "QUINE_EXEC_ENABLED"
	EnvSpawnEnabled             = "QUINE_SPAWN_ENABLED"
	EnvAgentsMDEnabled          = "QUINE_AGENTS_MD_ENABLED"
	EnvAgentsSkillsEnabled      = "QUINE_AGENTS_SKILLS_ENABLED"
	EnvVisionEnabled            = "QUINE_VISION_ENABLED"
	EnvShInteractiveEnabled     = "QUINE_SH_INTERACTIVE_ENABLED"
	EnvForkWorldEnabled         = "QUINE_FORK_WORLD_ENABLED"
	EnvEphemeralBodyEnabled     = "QUINE_EPHEMERAL_BODY_ENABLED"
	EnvSuppressInitialBegin     = "QUINE_SUPPRESS_INITIAL_BEGIN"
	EnvInitialUserMessage       = "QUINE_INITIAL_USER_MESSAGE"
	EnvSelfSourceCodeEnabled    = "QUINE_SELF_SOURCE_CODE_ENABLED"
	EnvSmartModelID             = "QUINE_SMART_MODEL_ID"
	EnvSmartAPIKey              = "QUINE_SMART_API_KEY"
	EnvSmartAPIBase             = "QUINE_SMART_API_BASE"
	EnvSmartAPIType             = "QUINE_SMART_API_TYPE"
	EnvStallThreshold           = "QUINE_STALL_THRESHOLD"
	EnvUserAgent                = "QUINE_USER_AGENT"
	EnvContextTape              = "QUINE_CONTEXT_TAPE"
	EnvWorkspaceRoot            = "QUINE_WORKSPACE_ROOT"
	EnvWorkspace                = "QUINE_WORKSPACE"
	EnvWorkspaceBackend         = "QUINE_WORKSPACE_BACKEND"
	EnvWorkspaceOverlayDriver   = "QUINE_WORKSPACE_OVERLAY_DRIVER"
	EnvWorkspaceRevisionMode    = "QUINE_WORKSPACE_REVISION_MODE"
	EnvWorkspaceSession         = "QUINE_WORKSPACE_SESSION"
	EnvWorkspaceOwner           = "QUINE_WORKSPACE_OWNER"
	EnvWorkspaceCommitOnSignal  = "QUINE_WORKSPACE_COMMIT_ON_SIGNAL"
	EnvWorkspaceBootstrap       = "QUINE_WORKSPACE_BOOTSTRAP"
	EnvWorkspaceCurrentRevision = "QUINE_WORKSPACE_CURRENT_REVISION"
	EnvWorkspaceSource          = "QUINE_WORKSPACE_SOURCE"
	EnvWorldOnePerShell         = "QUINE_WORLD_ONE_PER_SHELL"
	EnvDebugRequestBodyDir      = "QUINE_DEBUG_REQUEST_BODY_DIR"
)

var ProcessIdentityEnvNames = []string{
	EnvSessionID,
	EnvRunID,
	EnvTapeID,
	EnvContextTape,
	EnvWorkspaceSession,
	EnvWorkspaceOwner,
	EnvWorkspaceBootstrap,
	EnvWorkspaceCurrentRevision,
}
